/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "INDEX_OUT.h"
#include "INDEX_OUT_aliases.h"
#include "INDEX_IN.h"
#include "INDEX_IN_aliases.h"
#include "HOME_OUT.h"
#include "HOME_OUT_aliases.h"
#include "HOME_IN.h"
#include "HOME_IN_aliases.h"
#include "SPI_1.h"
#include "SPI_1_SPI_UART.h"
#include "SPI_1_PINS.h"
#include "SPI_1_SPI_UART_PVT.h"
#include "SPI_1_PVT.h"
#include "SPI_1_BOOT.h"
#include "LED.h"
#include "LED_aliases.h"
#include "Clock_1.h"
#include "phiB.h"
#include "phiB_aliases.h"
#include "phiA.h"
#include "phiA_aliases.h"
#include "I2C.h"
#include "I2C_I2C.h"
#include "I2C_PINS.h"
#include "I2C_I2C_PVT.h"
#include "I2C_PVT.h"
#include "I2C_BOOT.h"
#include "Counter_1.h"
#include "Reset_Encoder.h"
#include "Reset_Encoder_aliases.h"
#include "Direction.h"
#include "Direction_aliases.h"
#include "isr_rst_encoder.h"
#include "isr_home.h"
#include "PWM_OUT.h"
#include "PWM_OUT_aliases.h"
#include "isr_spi_ss.h"
#include "spi_ss.h"
#include "spi_ss_aliases.h"
#include "spi_mosi.h"
#include "spi_mosi_aliases.h"
#include "spi_clk.h"
#include "spi_clk_aliases.h"
#include "spi_miso.h"
#include "spi_miso_aliases.h"
#include "PROBE.h"
#include "PROBE_aliases.h"
#include "PWM_1.h"
#include "SPI_1_SCBCLK.h"
#include "SPI_1_SCB_IRQ.h"
#include "I2C_SCBCLK.h"
#include "I2C_sda.h"
#include "I2C_sda_aliases.h"
#include "I2C_scl.h"
#include "I2C_scl_aliases.h"
#include "I2C_SCB_IRQ.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

